Wed Oct 28 17:17:11 CST 2020 : Servidor de red Apache Derby: Se ha iniciado 10.11.1.1 - (1616546) y está listo para aceptar las conexiones en el puerto 1527
----------------------------------------------------------------
Wed Oct 28 17:17:11 CST 2020:
 Iniciando instancia a816c00e-0175-7180-3d1b-00006f9453bf de Derby, versión The Apache Software Foundation - Apache Derby - 10.11.1.1 - (1616546): 
en el directorio de base de datos C:\Users\jefem\Documents\NetBeansProjects\ProyectoFinal\DB\ServicioMensajeria con el cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
Cargado desde file:/C:/Users/jefem/Documents/db-derby-10.11.1.1-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\jefem\Documents\db-derby-10.11.1.1-bin
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\jefem\Documents\NetBeansProjects\ProyectoFinal\DB
Cargador de clases de base de datos iniciado - derby.database.classpath=''
----------------------------------------------------------------
Wed Oct 28 17:17:19 CST 2020:
Cerrando la instancia a816c00e-0175-7180-3d1b-00006f9453bf en el directorio de base de datos C:\Users\jefem\Documents\NetBeansProjects\ProyectoFinal\DB\ServicioMensajeria con cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
Wed Oct 28 17:17:19 CST 2020 Thread[DRDAConnThread_2,5,main] (DATABASE = ServicioMensajeria), (DRDAID = {2}), Cierre de la base de datos 'ServicioMensajeria'.
Wed Oct 28 17:18:37 CST 2020 Thread[DRDAConnThread_2,5,main] Cleanup action starting
java.sql.SQLException: No se ha encontrado la base de datos 'sample'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: No se ha encontrado la base de datos 'sample'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: No se ha encontrado la base de datos 'sample'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Oct 28 17:18:37 CST 2020 Thread[DRDAConnThread_2,5,main] (DATABASE = sample), (DRDAID = {3}), No se ha encontrado la base de datos 'sample'.
Wed Oct 28 17:18:50 CST 2020 Thread[DRDAConnThread_2,5,main] Cleanup action starting
java.sql.SQLException: No se ha encontrado la base de datos 'sample'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ004: No se ha encontrado la base de datos 'sample'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: No se ha encontrado la base de datos 'sample'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Wed Oct 28 17:18:50 CST 2020 Thread[DRDAConnThread_2,5,main] (DATABASE = sample), (DRDAID = {4}), No se ha encontrado la base de datos 'sample'.
----------------------------------------------------------------
Wed Oct 28 17:19:11 CST 2020:
 Iniciando instancia a65c80ac-0175-7180-3d1b-00006f9453bf de Derby, versión The Apache Software Foundation - Apache Derby - 10.11.1.1 - (1616546): 
en el directorio de base de datos C:\Users\jefem\Documents\NetBeansProjects\ProyectoFinal\DB\ServicioMensajeria con el cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
Cargado desde file:/C:/Users/jefem/Documents/db-derby-10.11.1.1-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\jefem\Documents\db-derby-10.11.1.1-bin
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\jefem\Documents\NetBeansProjects\ProyectoFinal\DB
Cargador de clases de base de datos iniciado - derby.database.classpath=''
----------------------------------------------------------------
Wed Oct 28 22:33:36 CST 2020:
 Iniciando instancia 83c08175-0175-7180-3d1b-00006f9453bf de Derby, versión The Apache Software Foundation - Apache Derby - 10.11.1.1 - (1616546): 
en el directorio de base de datos C:\Users\jefem\Documents\NetBeansProjects\ProyectoFinal\DB\ServiciMensajeria con el cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
Cargado desde file:/C:/Users/jefem/Documents/db-derby-10.11.1.1-bin/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Users\jefem\Documents\db-derby-10.11.1.1-bin
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\jefem\Documents\NetBeansProjects\ProyectoFinal\DB
Cargador de clases de base de datos iniciado - derby.database.classpath=''
----------------------------------------------------------------
Wed Oct 28 22:40:44 CST 2020: cerrando motor de Derby
----------------------------------------------------------------
Wed Oct 28 22:40:44 CST 2020:
Cerrando la instancia 83c08175-0175-7180-3d1b-00006f9453bf en el directorio de base de datos C:\Users\jefem\Documents\NetBeansProjects\ProyectoFinal\DB\ServiciMensajeria con cargador de clases sun.misc.Launcher$AppClassLoader@6f94fa3e
